"""Markdown report generation — readable by the supervisor on GitHub."""
from __future__ import annotations

from pathlib import Path

import pandas as pd


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:,.3f}"
    return str(v)


def _dict_table(d: dict) -> str:
    lines = ["| Quantity | Value |", "|---|---|"]
    lines += [f"| {k} | {_fmt(v)} |" for k, v in d.items()]
    return "\n".join(lines)


def write_report(path: Path, *, title: str, quality: dict, totals: dict,
                 solar: dict, balance: dict, flow_meta: dict,
                 binned: pd.DataFrame, daily: pd.DataFrame,
                 figures: list[str], hx_balance: dict | None = None,
                 store_balance: dict | None = None) -> None:
    import datetime
    import os
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC")
    sha = os.environ.get("GITHUB_SHA", "local")[:9]
    md = [f"# {title}", "",
          f"_Run: {stamp} · code+data revision `{sha}`. Every pipeline run "
          f"rewrites this stamp, so a fresh commit here proves the analysis "
          f"actually ran on your upload._", ""]

    md += ["## Data quality", "", _dict_table(quality), ""]

    md += ["## Measured-period totals", "",
           "**Not full-season totals** — integrals cover only instrumented "
           "periods (see coverage figures); no extrapolation is applied.", ""]
    if totals:
        md += [_dict_table(totals), ""]
    else:
        md += ["_No flow-dependent totals available (air flow missing)._", ""]
    if flow_meta:
        md += [f"_Air-flow sources: process = {flow_meta.get('flow_source_proc')}, "
               f"regeneration = {flow_meta.get('flow_source_reg')}._", ""]

    md += ["## Solar contribution", "", _dict_table(solar) if solar else
           "_Not computable._", ""]

    md += ["## Energy-balance closure", "",
           _dict_table(balance) if balance else "_Not computable._", ""]

    md += ["## Air-to-water HX balance (regeneration coil)", "",
           "Boundary = regeneration heating coil. Water side "
           "(`Q_hx_water` = circuit-III heat given up) vs air side "
           "(`Q_hx_air` = regeneration-air sensible gain across the coil). "
           "`hx_closure = Q_hx_air / Q_hx_water` — expected ≈ 0.8–1.0; the "
           "air side needs the ch 120 regeneration air flow, so the closure "
           "covers only the window where both sides are measured.", ""]
    md += [_dict_table(hx_balance) if hx_balance else "_Not computable._", ""]

    md += ["## Thermal-storage balance (energy in vs out + ΔU)", "",
           "Boundary = stratified store. Charge (`Q_store_in`, circuit II) "
           "vs discharge (`Q_store_out`, circuit III = regeneration heat) "
           "plus the stored-energy change ΔU from the SP layer temperatures. "
           "Absolute ΔU, standby loss and closure require the tank volume "
           "(`config.STORAGE_VOLUME_M3`); until then ΔU is reported per m³.",
           ""]
    md += [_dict_table(store_balance) if store_balance else "_Not computable._",
           ""]

    if not binned.empty:
        md += ["## KPIs by regeneration temperature bin", "",
               binned.to_markdown(index=False, floatfmt=".3f"), ""]

    if not daily.empty:
        md += ["## Daily summary", "",
               daily.round(3).to_markdown(), ""]

    if figures:
        md += ["## Figures", ""]
        md += [f"![{Path(f).stem}]({f})" for f in figures]
        md += [""]

    md += ["---",
           "_Auto-generated by dw-analysis. KPI definitions and sources: "
           "see docs/KPI_DEFINITIONS.md._"]
    path.write_text("\n".join(md), encoding="utf-8")
