"""Markdown report generation — readable by the supervisor on GitHub."""
from __future__ import annotations

from pathlib import Path

import pandas as pd


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:,.3f}"
    return str(v)


def _dict_table(d: dict) -> str:
    lines = ["| Quantity | Value |", "|---|---|"]
    lines += [f"| {k} | {_fmt(v)} |" for k, v in d.items()]
    return "\n".join(lines)


def write_report(path: Path, *, title: str, quality: dict, totals: dict,
                 solar: dict, balance: dict, flow_meta: dict,
                 binned: pd.DataFrame, daily: pd.DataFrame,
                 figures: list[str]) -> None:
    md = [f"# {title}", ""]

    md += ["## Data quality", "", _dict_table(quality), ""]

    md += ["## Season / period totals", ""]
    if totals:
        md += [_dict_table(totals), ""]
    else:
        md += ["_No flow-dependent totals available (air flow missing)._", ""]
    if flow_meta:
        md += [f"_Air-flow sources: process = {flow_meta.get('flow_source_proc')}, "
               f"regeneration = {flow_meta.get('flow_source_reg')}._", ""]

    md += ["## Solar contribution", "", _dict_table(solar) if solar else
           "_Not computable._", ""]

    md += ["## Energy-balance closure", "",
           _dict_table(balance) if balance else "_Not computable._", ""]

    if not binned.empty:
        md += ["## KPIs by regeneration temperature bin", "",
               binned.to_markdown(index=False, floatfmt=".3f"), ""]

    if not daily.empty:
        md += ["## Daily summary", "",
               daily.round(3).to_markdown(), ""]

    if figures:
        md += ["## Figures", ""]
        md += [f"![{Path(f).stem}]({f})" for f in figures]
        md += [""]

    md += ["---",
           "_Auto-generated by dw-analysis. KPI definitions and sources: "
           "see docs/KPI_DEFINITIONS.md._"]
    path.write_text("\n".join(md), encoding="utf-8")
